#machine:

 #dependencies:
  #cache_directories:
 #pre:
  #override:
    #- apt-get update && apt-get install python3 python2
    #- pip install -r requirements.txt
    #- pip install flake8 tox

#test:
  #override:
    #- tox
    #- flake8 --config flake8 uplink
    #- '! grep -P pdb */*.py'

version: 2
jobs:
  py2:
    docker:
      - image: circleci/python:2
    steps:
      - checkout
      - run: sudo pip install pipenv
      - run: pipenv --two install
      - run: pipenv run pytest -vv -s tests
  py3:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: sudo pip install pipenv
      - run: pipenv --three install
      - run: pipenv run pytest -vv -s tests

  typecheck:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: sudo pip install mypy
      - run: sudo mypy --ignore-missing-imports uplink integration_tests tests


workflows:
  version: 2
  test:
    jobs:
      - py2
      - py3
      - typecheck
